document.addEventListener('DOMContentLoaded',()=>{
 const nav=document.querySelector('.nav'),menu=document.querySelector('.menu');
 menu?.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});
 const cur=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.links a').forEach(a=>{if(a.getAttribute('href')===cur)a.classList.add('active')});
 const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
 document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count,s=el.dataset.suffix||'';const o=new IntersectionObserver(es=>{if(!es[0].isIntersecting)return;o.disconnect();if(matchMedia('(prefers-reduced-motion:reduce)').matches){el.textContent=target.toLocaleString()+s;return}let t0;function f(t){t0??=t;let p=Math.min((t-t0)/1100,1),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=v.toLocaleString()+s;if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)},{threshold:.8});o.observe(el)});
 const modal=document.querySelector('.modal');document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>modal?.classList.add('open')));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});modal?.querySelector('.close')?.addEventListener('click',()=>modal.classList.remove('open'));document.addEventListener('keydown',e=>{if(e.key==='Escape')modal?.classList.remove('open')});
 document.querySelectorAll('[data-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();if(!f.checkValidity()){f.reportValidity();return}let n=f.querySelector('.notice');if(n){n.textContent='Thanks — your request has been received. Connect this form to your backend or CRM for production use.';n.style.display='block'}f.reset()}));
 document.querySelectorAll('[data-filter-group]').forEach(g=>{let buttons=g.querySelectorAll('.filter'),cards=g.parentElement.querySelectorAll('[data-cat]');buttons.forEach(b=>b.onclick=()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');let v=b.dataset.filter;cards.forEach(c=>c.style.display=v==='all'||c.dataset.cat.split(' ').includes(v)?'':'none')})});
 const rs=document.querySelector('[data-resource-search]');if(rs){let cs=document.querySelectorAll('[data-resource]');rs.oninput=()=>{let q=rs.value.toLowerCase();cs.forEach(c=>c.style.display=!q||c.textContent.toLowerCase().includes(q)?'':'none')}}
 document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>{let t=document.querySelector('.toast');t.textContent=b.dataset.toast;t.style.display='block';setTimeout(()=>t.style.display='none',3000)});
});
